### ISSUE TITLE
where can I find the file "features_69612_0709_spacy_lg_zero_multiclasses_filtered.npy"

### ISSUE THREAD

**Issue by YYYYWD** [YuweiCao-UIC/KPGNN#1]
thanks

**Comment by YuweiCao-UIC** [comment]
Hi, thank you for your interest. The file is too large to be uploaded. Please use generate_initial_features.py to generate the file.

**Comment by YYYYWD** [comment]
Thanks for your answer, your code helped me a lot. Although I haven't run successfully yet.  haha
Similar to some functions and the numbers followed by the data set path, such as 0808, 0722, 0922, does it mean that they are functions of different periods(versions)? But in fact, their purpose is the same.

**Comment by YuweiCao-UIC** [comment]
Yes, the numbers indicate different versions.

**Comment by YYYYWD** [comment]
Thank you for your help.  I can already run the code successfully
